### ISSUE TITLE
Error in Select - AS (column aliases) query builder documentation

### ISSUE THREAD

**Issue by kwn** [kohana/database#87]
I found an error in kohana doc in /guide/database/query/builder file

```
$query = DB::select(array('username', 'u'), array('password', 'p'))->from('users');
```

sould be

```
$query = DB::select(array(array('username', 'u'), array('password', 'p')))->from('users');
```

**Comment by enov** [comment]
I think the docs are correct. `func_get_args` returns an array of arguments.

https://github.com/kohana/database/blob/3.3/master/classes/Kohana/DB.php#L62

**Comment by Asenar** [comment]
the documentation is correct

**Comment by kwn** [comment]
Oops, I used a Select() method with constructor Select::_construct, not through DB factory(?)
